import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  // Absolute origin (no path). Placeholder Netlify URL for the manager
  // preview — swap for the real domain when one is assigned.
  site: 'https://community-engagement.netlify.app',
  output: 'static',
  trailingSlash: 'always',
  build: {
    // Inline CSS into the document so there's no render-blocking stylesheet
    // request (single-page site → no cross-page cache benefit lost). Lifts
    // mobile FCP/Performance.
    inlineStylesheets: 'always',
  },
  // Tailwind 4 ships as a Vite plugin (not the v3 PostCSS pipeline).
  vite: {
    plugins: [tailwindcss()],
  },
  // Sitemap is generated by the native src/pages/sitemap.xml.ts route so it
  // resolves at /sitemap.xml. Astro image optimization (astro:assets) is built
  // in; `sharp` is installed + allow-listed so <Image>/<Picture> work.
});
